version: "3.9"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
  web:
    build: 
      context: .
    command: "python manage.py migrate &&
              python manage.py wait_for_db &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./code:/code
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis: 
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l info
    volumes:
    - ./code:/code
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web