version: "3.9"

services:
  db:
    image: postgres:10-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=badstar55
    ports:
      - "5432:5432"
  web:
    build: 
      context: .
    command: "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./code:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
