version: "3.9"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
  web:
    stdin_open: true
    tty: true
    build: 
      context: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py wait_for_db &&
             python manage.py collectstatic && 
             uwsgi --ini dyad_uwsgi.ini"
    volumes:
      - ./code:/code
    env_file:
      - ./.env.dev
    ports:
            - "8001:8001"
    depends_on:
      - db
  redis: 
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l info
    volumes:
    - ./code:/code
    - /tmp/dyad:/tmp
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web
