# Generated by Django 3.2.9 on 2022-04-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('post_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
