# Generated by Django 3.2.9 on 2021-12-06 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_group_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group_key',
        ),
    ]
