# Generated by Django 3.2.9 on 2021-12-06 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dyadgroup'),
        ('api', '0003_remove_post_group_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group_key',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dyadgroup'),
        ),
    ]
