# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontent.proto\"5\n\x07\x43ontent\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\x05image\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_imageb\x06proto3')



_CONTENT = DESCRIPTOR.message_types_by_name['Content']
Content = _reflection.GeneratedProtocolMessageType('Content', (_message.Message,), {
  'DESCRIPTOR' : _CONTENT,
  '__module__' : 'content_pb2'
  # @@protoc_insertion_point(class_scope:Content)
  })
_sym_db.RegisterMessage(Content)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTENT._serialized_start=17
  _CONTENT._serialized_end=70
# @@protoc_insertion_point(module_scope)
