# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gens.count_pb2 as count__pb2


class ActiveUsersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getRecentlyActive = channel.unary_stream(
                '/ActiveUsers/getRecentlyActive',
                request_serializer=count__pb2.ActiveQuery.SerializeToString,
                response_deserializer=count__pb2.Count.FromString,
                )


class ActiveUsersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getRecentlyActive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActiveUsersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getRecentlyActive': grpc.unary_stream_rpc_method_handler(
                    servicer.getRecentlyActive,
                    request_deserializer=count__pb2.ActiveQuery.FromString,
                    response_serializer=count__pb2.Count.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ActiveUsers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ActiveUsers(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getRecentlyActive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ActiveUsers/getRecentlyActive',
            count__pb2.ActiveQuery.SerializeToString,
            count__pb2.Count.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
