# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: count.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63ount.proto\"\x16\n\x05\x43ount\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\" \n\x0b\x41\x63tiveQuery\x12\x11\n\trequestor\x18\x01 \x01(\t2:\n\x0b\x41\x63tiveUsers\x12+\n\x11getRecentlyActive\x12\x0c.ActiveQuery\x1a\x06.Count0\x01\x62\x06proto3')



_COUNT = DESCRIPTOR.message_types_by_name['Count']
_ACTIVEQUERY = DESCRIPTOR.message_types_by_name['ActiveQuery']
Count = _reflection.GeneratedProtocolMessageType('Count', (_message.Message,), {
  'DESCRIPTOR' : _COUNT,
  '__module__' : 'count_pb2'
  # @@protoc_insertion_point(class_scope:Count)
  })
_sym_db.RegisterMessage(Count)

ActiveQuery = _reflection.GeneratedProtocolMessageType('ActiveQuery', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVEQUERY,
  '__module__' : 'count_pb2'
  # @@protoc_insertion_point(class_scope:ActiveQuery)
  })
_sym_db.RegisterMessage(ActiveQuery)

_ACTIVEUSERS = DESCRIPTOR.services_by_name['ActiveUsers']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COUNT._serialized_start=15
  _COUNT._serialized_end=37
  _ACTIVEQUERY._serialized_start=39
  _ACTIVEQUERY._serialized_end=71
  _ACTIVEUSERS._serialized_start=73
  _ACTIVEUSERS._serialized_end=131
# @@protoc_insertion_point(module_scope)
