# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: posts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bposts.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x01\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x30\n\x0clast_updated\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07\x63reated\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05title\x18\x06 \x01(\t\x12\r\n\x05group\x18\x07 \x01(\t\"4\n\tPostQuery\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0b\n\x03gid\x18\x06 \x01(\t\"K\n\rPostUploadAck\x12\n\n\x02id\x18\x01 \x01(\x05\x12.\n\nsaved_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"&\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04hwid\x18\x02 \x01(\t2{\n\tPostsSync\x12#\n\x0crefreshPosts\x12\n.PostQuery\x1a\x05.Post0\x01\x12!\n\nqueryPosts\x12\n.PostQuery\x1a\x05.Post0\x01\x12&\n\x0buploadPosts\x12\x05.Post\x1a\x0e.PostUploadAck(\x01\x62\x06proto3')



_POST = DESCRIPTOR.message_types_by_name['Post']
_POSTQUERY = DESCRIPTOR.message_types_by_name['PostQuery']
_POSTUPLOADACK = DESCRIPTOR.message_types_by_name['PostUploadAck']
_USER = DESCRIPTOR.message_types_by_name['User']
Post = _reflection.GeneratedProtocolMessageType('Post', (_message.Message,), {
  'DESCRIPTOR' : _POST,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:Post)
  })
_sym_db.RegisterMessage(Post)

PostQuery = _reflection.GeneratedProtocolMessageType('PostQuery', (_message.Message,), {
  'DESCRIPTOR' : _POSTQUERY,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:PostQuery)
  })
_sym_db.RegisterMessage(PostQuery)

PostUploadAck = _reflection.GeneratedProtocolMessageType('PostUploadAck', (_message.Message,), {
  'DESCRIPTOR' : _POSTUPLOADACK,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:PostUploadAck)
  })
_sym_db.RegisterMessage(PostUploadAck)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'posts_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

_POSTSSYNC = DESCRIPTOR.services_by_name['PostsSync']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POST._serialized_start=49
  _POST._serialized_end=225
  _POSTQUERY._serialized_start=227
  _POSTQUERY._serialized_end=279
  _POSTUPLOADACK._serialized_start=281
  _POSTUPLOADACK._serialized_end=356
  _USER._serialized_start=358
  _USER._serialized_end=396
  _POSTSSYNC._serialized_start=398
  _POSTSSYNC._serialized_end=521
# @@protoc_insertion_point(module_scope)
