# Generated by Django 3.2.9 on 2021-12-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dyaduser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dyaduser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='dyaduser',
            name='password',
        ),
        migrations.AddField(
            model_name='dyaduser',
            name='email',
            field=models.EmailField(default='NA', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dyaduser',
            name='user',
            field=models.CharField(default='NA', max_length=24, unique=True),
            preserve_default=False,
        ),
    ]
