# Generated by Django 3.2.9 on 2021-12-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211205_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dyaduser',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='dyaduser',
            name='first_name',
            field=models.CharField(default='NA', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dyaduser',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dyaduser',
            name='is_staff',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dyaduser',
            name='is_superuser',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dyaduser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dyaduser',
            name='last_name',
            field=models.CharField(default='NA', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dyaduser',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
