# Generated by Django 3.2.9 on 2021-12-06 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dyaduser_dyad_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyaduser',
            name='Dyad_Group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.dyadgroup'),
        ),
    ]
