# Generated by Django 3.2.9 on 2021-12-06 02:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_dyadgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dyaduser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='dyaduser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='dyaduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dyaduser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dyaduser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dyaduser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dyaduser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='dyaduser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='dyaduser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='dyaduser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='dyaduser',
            name='username',
        ),
        migrations.AddField(
            model_name='dyaduser',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
    ]
